color:
  chart:
    stacked:
      base:
        '100':
          value: "{color.blue.1.value}"
        '200':
          value: "{color.blue.2.value}"
        '300':
          value: "{color.blue.3.value}"
        '400':
          value: "{color.blue.4.value}"
        '500':
          value: "{color.blue.5.value}"
        '600':
          value: "{color.blue.6.value}"
        '700':
          value: "{color.blue.7.value}"
        '800':
          value: "{color.blue.8.value}"
        '900':
          value: "{color.blue.9.value}"
